services:
  forge-test-postgres:
    image: postgres:17
    container_name: forge-test-postgres
    command: ["postgres", "-c", "log_statement=all", "-c", "log_min_duration_statement=0", "-c", "shared_buffers=256MB", "-c", "max_connections=200"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
